### ISSUE TITLE
toolbar height is to small

### ISSUE THREAD

**Issue by soundslikeodd** [riemann/riemann-dash#110]
Currently the height of the toolbar div is to small.  If there are many tabs they wrap and are hidden by the view div.  Both the toolbar and the view have absolute positions.  
There are two possible solutions.  
1. Might the height of the toolbar div and position of the view div larger (lets say 100px).  
2. Since the content is dynamically created, the toolbar div and position of the view div can be adjust appropriately.

**Comment by soundslikeodd** [comment]
I have created a pull request with the 1st proposal in place.
https://github.com/aphyr/riemann-dash/pull/111

**Comment by mfournier** [comment]
Thanks for reporting this @soundslikeodd !

I gave a try to #111 but I must say I find this large blank a bit of a waste of space when you only have one row of tabs. Did you already look into what solution 2 involves ?

Thanks !

**Comment by aphyr** [comment]
Yeah, I'd say either adjust the toolbar height dynamically, or we do a tab-completable dropdown with the full list, and keep the most frequently used workspaces in the top list.

**Comment by soundslikeodd** [comment]
I agree that solution 2 is the better solution.  I am not a the best at front end dev work so the 1st solution was the quickest for me to spin up.  I can come up with a sample for the 2nd solution but it might take me a bit.

I like the tabs or a dropdown because it is quicker to switch between workspaces.  Putting the most frequently used on top is a good way to mitigate this issue but it would still take some time to find a workspace if there are a large number of them.

**Comment by soundslikeodd** [comment]
I have a rough implementation for the 2nd solution.
https://github.com/riemann/riemann-dash/pull/112

**Comment by mfournier** [comment]
Closed by #112, thanks ! For the record, this fix will be part of upcoming version 0.2.13.
