### ISSUE TITLE
How to start with the dashboard? 

### ISSUE THREAD

**Issue by bluepuma77** [riemann/riemann-dash#121]
I was very excited about Riemann when I watched the talk on the [Riemann homepage](http://riemann.io/). I thought it would solve all my problems, but I can't get the visualization of the dashboard to run.

I have been testing `riemann-dash` via Docker containers, I tried [rlister/riemann-dash](https://hub.docker.com/r/rlister/riemann-dash/) and building my own container according to the blog entry ["Realtime Cluster Monitoring With Docker Swarm And Riemann"](https://blog.docker.com/2016/03/realtime-cluster-monitoring-docker-swarm-riemann/).

The challenge I am facing is that I can't edit anything. The dashboard comes up, I am supposed to press "e", but nothing happens. I am using OS X, I tried activating views (I assume that means tabs) with alt-cmd-click, still I cant do anything via "e". I changed the address to the Riemann server, nothing happens. (Tested the address with telnet, I can connect, so server seems to be running). I watched a tutorial, but for me the edit window never shows up. Tested in Chrome, Firefox and Safari on OS X. No error messages in the console.

What am I missing? 

![riemann-dash](https://cloud.githubusercontent.com/assets/5221187/17052544/401e1e2a-4ffe-11e6-9687-09bf3cdb0de3.png)

**Comment by aphyr** [comment]
On 07/22/2016 04:24 AM, bluepuma77 wrote:
> views (I assume that means tabs)

You... probably already tried this, but just to make sure, did you follow the 
quickstart's directions for editing a view?

 > Let's change the title into a Grid view. Hold CTRL (or OPTION/META depending
 > on your OS) and click the big title "Riemann" in the top pane. The title will
 > be shaded grey to indicate that view is selected.

 > Then, press "e" to edit, and change "Title" to "Grid". We need to choose a
 > query to select specific states from the index. For starters, let's select
 > everything by typing true in the query field. Hit "Apply" when you're ready.

http://riemann.io/quickstart.html

**Comment by bluepuma77** [comment]
I did not read that piece - I always clicked on the tabs. It did not occur to me to click on the big letters. Thank you very much for the hint :-)
