### ISSUE TITLE
Unit tests currently broken?

### ISSUE THREAD

**Issue by andeemarks** [riemann/riemann-dash#86]
Hi All,
Running '''sh/test''' gives me the following results:

`12 tests, 19 assertions, 0 failures, 3 errors, 0 skips`

The three broken tests are all attempting to access methods in `Riemann::Dash::Config` which were removed in a previous commit, specifically `update_ws_config` and `read_ws_config`

The specific failling tests are:

    1) Error:
    test_0001_reads the file, if present(Riemann::Dash::Config::workspace config::read_ws_config):
    NoMethodError: undefined method `read_ws_config' for #<Riemann::Dash::Config:0x007fe52a10ce28>
    /Users/amarks/Code/riemann/riemann-dash/test/config_test.rb:86:in `block (4 levels) in <top (required)>'
    [...]

    2) Error:
    test_0001_works(Riemann::Dash::Config::workspace config::update_ws_config):
    NoMethodError: undefined method `update_ws_config' for     #<Riemann::Dash::Config:0x007fe52a1162e8>
    /Users/amarks/Code/riemann/riemann-dash/test/config_test.rb:93:in `block (4 levels) in <top (required)>'
    [...]

    3) Error:
    test_0002_pretty-prints the config(Riemann::Dash::Config::workspace config::update_ws_config):
    NoMethodError: undefined method `update_ws_config' for #<Riemann::Dash::Config:0x007fe52a15c900>
    /Users/amarks/Code/riemann/riemann-dash/test/config_test.rb:98:in `block (4 levels) in <top (required)>'
    [...]

Note: this is my first time running these tests, so it's possible I have a configuration issue behind these problems.

My environment:

`~/C/r/riemann-dash ❯❯❯ ruby -v`
`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

`~/C/r/riemann-dash ❯❯❯ sh/c`
`irb(main):001:0> Riemann::Dash::VERSION`
`=> "0.2.9"``

**Comment by mfournier** [comment]
Current master says `18 tests, 27 assertions, 0 failures, 0 errors, 0 skips`, so we're all good. Closing.
