### ISSUE TITLE
Provide support for the latest version of gem thin.

### ISSUE THREAD

**Issue by ghanima** [riemann/riemann-dash#92]
Came across this error after install riemann-dash via the gem method.

No configuration loaded; using defaults.
/home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thin-2.0.0.pre/lib/thin/server.rb:108:in `initialize': wrong number of arguments (4 for 0..3) (ArgumentError)
	from /home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:14:in `new'
	from /home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/thin.rb:14:in `run'
	from /home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1497:in `start_server'
	from /home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1435:in `run!'
	from /home/chancock/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/riemann-dash-0.2.11/bin/riemann-dash:7:in `<top (required)>'
	from /home/chancock/.rbenv/versions/2.1.2/bin/riemann-dash:23:in `load'
	from /home/chancock/.rbenv/versions/2.1.2/bin/riemann-dash:23:in `<main>'

From my research this error is specific to the latest version of thin that is available via rubygems. Recommend that a dependency be set for specific Thin version lower than 2.2.0.pre or see if work can be done to start using the latest version of Thin.

if I have some cycles I will try to take a look and see if I can submit a patch.

Please let me know if I can provide any additional information.

**Comment by mfournier** [comment]
-1 for re-adding the dependency on thin. See #65, #66, #82.

@ghanima out of curiosity, which version of riemann-dash did you install ?
