### ISSUE TITLE
Key bindings not working on OS X

### ISSUE THREAD

**Issue by sofam** [riemann/riemann-dash#97]
None of the keyboard bindings work on OS X in Safari, Firefox or Chrome. 'e' doesn't work at all. Nothing in the console about what's broken. 

Have you seen it before or something?

**Comment by jnbdz** [comment]
Try <option>+<command>+<mouse click>.

**Comment by timurb** [comment]
option+command+mouse click works fine however docs say "Press Control/Meta+click to select a view" (so do the tutorials).
Should we update the docs?

**Comment by rclayton-the-terrible** [comment]
I'm having a heck of a time trying to use the Dashboard.  I can't seem to get to the edit window on OSX, even with Control-Option-Mouse Left Click.  Pressing "e" does nothing.  Am I doing something wrong?
